# Tensors

In [1]:
print("Tensors")

Tensors


- In Pytorch, we use tensors to encode inputs and outputs of a model as well as the models' paramters

- Tensors can run on GPUs or other hardware accelerators. 
- Tensors are optimized for automatic differentiation.
- Tensors and numpy can share the same underlying memory, eliminating the need to copy data.

In [3]:
import torch
import numpy as np

In [4]:
# Initializing tensor: directly from data
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [6]:
# Initializing tensor: From a numpy array
n = np.array(data)
x_t = torch.from_numpy(n)
print(x_t)

tensor([[1, 2],
        [3, 4]])


In [ ]:
# Initializing Tensor: from another tensor
x_ones = torch.ones_like(x_data)    # retains properties of x_data
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)     # overrides the datatype of x_data
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.3703, 0.4064],
        [0.8591, 0.4619]])


We can use pre-defined tensor dimensions using tuple.
 

In [8]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.9663, 0.2716, 0.9940],
        [0.8139, 0.1374, 0.1878]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


Tensor attributes describe their shape, datatype and the device on which they are stored.

In [9]:
tensor = torch.rand(3,2)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of a tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 2])
Datatype of a tensor: torch.float32
Device tensor is stored on: cpu


- 1200 tensor operations including arithmetic, linear algebra, matrix multiplication (transposing, indexing, slicing), sampling and more are present.
- By default, tensors are created on the CPU. We need to ecplicitly move tensors to the accelerator using `.to()` method (after checking accelerator availability).

In [10]:
# Move the tensor to the accelerator if it is available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
print(tensor)

tensor([[0.3005, 0.8623],
        [0.2040, 0.1702],
        [0.1446, 0.6583]], device='mps:0')


Standard Numpy like Indexing

In [11]:
tensor = torch.ones(4,4)

print(f"First row: {tensor[0]}")
print(f"First Column: {tensor[:,0]}")
print(f"Last Column: {tensor[...,-1]}")
tensor[:,1] = 5
print(tensor)

First row: tensor([1., 1., 1., 1.])
First Column: tensor([1., 1., 1., 1.])
Last Column: tensor([1., 1., 1., 1.])
tensor([[1., 5., 1., 1.],
        [1., 5., 1., 1.],
        [1., 5., 1., 1.],
        [1., 5., 1., 1.]])


- Use `torch.cat` to concatenate a sequence of tensors along a given dimension.

In [12]:
t1 = torch.cat([tensor, tensor.T, tensor], dim=1)
print(t1)

tensor([[1., 5., 1., 1., 1., 1., 1., 1., 1., 5., 1., 1.],
        [1., 5., 1., 1., 5., 5., 5., 5., 1., 5., 1., 1.],
        [1., 5., 1., 1., 1., 1., 1., 1., 1., 5., 1., 1.],
        [1., 5., 1., 1., 1., 1., 1., 1., 1., 5., 1., 1.]])


#### Arithmetic Operations

In [15]:
y1 = tensor @ tensor.T
print(y1)

y2 = tensor.matmul(tensor.T)
print(y2)

y3 = torch.rand_like(y1)
print(y3)
torch.matmul(tensor, tensor.T, out=y3)

print(y3)

# Compute element wise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor.T, out=z3)
print(z3)

tensor([[28., 28., 28., 28.],
        [28., 28., 28., 28.],
        [28., 28., 28., 28.],
        [28., 28., 28., 28.]])
tensor([[28., 28., 28., 28.],
        [28., 28., 28., 28.],
        [28., 28., 28., 28.],
        [28., 28., 28., 28.]])
tensor([[0.3922, 0.2477, 0.0152, 0.7304],
        [0.7095, 0.9038, 0.3672, 0.9344],
        [0.3671, 0.2024, 0.4035, 0.4287],
        [0.8545, 0.7422, 0.7176, 0.7363]])
tensor([[28., 28., 28., 28.],
        [28., 28., 28., 28.],
        [28., 28., 28., 28.],
        [28., 28., 28., 28.]])
tensor([[ 1.,  5.,  1.,  1.],
        [ 5., 25.,  5.,  5.],
        [ 1.,  5.,  1.,  1.],
        [ 1.,  5.,  1.,  1.]])


*Single-element tensors*: If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using `item()`

In [16]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

32.0 <class 'float'>


*Inplace Operations*: Operations that store the result into the operand are called in-place. They are denoted by _ suffix. eg: x.copy_(y), x.t_() will change x.

In [19]:
print(tensor)

tensor.t_()
print(tensor)

tensor([[1., 1., 1., 1.],
        [5., 5., 5., 5.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 5., 1., 1.],
        [1., 5., 1., 1.],
        [1., 5., 1., 1.],
        [1., 5., 1., 1.]])


Note: inplace operations saves some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

Tensors on the CPU and Numpy arrays can share their underlying memory locations, changing one will change another.


In [20]:
t = torch.ones(5)
print(t)

n = t.numpy()
print(n)

t.add_(1)
print(t)

print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
n = np.ones(10)
t = torch.from_numpy(n)
print(n)
print(t)

np.add(n,3, out=n)
print(n)
print(t)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
tensor([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.], dtype=torch.float64)
