# Introduction to Pytorch Tensors

In [1]:
import torch 
import math 

The rules for broadcasting are:

- Each tensor must have at least one dimension - no empty tensors.

- Comparing the dimension sizes of the two tensors, going from last to first:

    - Each dimension must be equal, or

    - One of the dimensions must be of size 1, or

    - The dimension does not exist in one of the tensors



In [2]:
x = torch.empty(3,4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


A brief note about tensors and their number of dimensions, and terminology:

- You will sometimes see a 1-dimensional tensor called a vector.

- Likewise, a 2-dimensional tensor is often referred to as a matrix.

- Anything with more than two dimensions is generally just called a tensor.



In [4]:
zeros = torch.zeros(2,3)
print(zeros)

ones = torch.ones(2,3)
print(ones)

torch.manual_seed(100)
random = torch.rand(2,3)
print(random)

torch.manual_seed(1729)
random = torch.rand(2,3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


## Tensor Shapes

In [8]:
x = torch.rand((1,2,11))
print(x.shape)

empty_like_x = torch.empty_like(x)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x)

onees_like_x = torch.ones_like(x)
print(onees_like_x)


torch.Size([1, 2, 11])
tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])
tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])


In [10]:
more_integers = torch.tensor(((2,4,6), [3,6,9]))
print(more_integers)

tensor([[2, 4, 6],
        [3, 6, 9]])


Using torch.tensor() is the most straightforward way to create a tensor if you already have data in a Python tuple or list. As shown above, nesting the collections will result in a multi-dimensional tensor.

`torch.tensor()` creates a copy of the data.

In [11]:
b = torch.rand((2,7), dtype=torch.float64) + 7 * 10 / 64
print(b)

c = b.to(torch.int16)
print(c)

tensor([[1.1528, 1.1844, 1.9394, 1.4087, 1.8121, 1.1060, 2.0313],
        [1.4106, 1.6721, 1.6179, 1.3059, 1.7067, 1.6244, 1.5247]],
       dtype=torch.float64)
tensor([[1, 1, 1, 1, 1, 1, 2],
        [1, 1, 1, 1, 1, 1, 1]], dtype=torch.int16)


## Tensor Broadcasting

In [12]:
rand = torch.rand(2,4)
doubled = rand * (torch.ones(1,4) * 2)

print(rand)
print(doubled)

tensor([[0.6264, 0.4704, 0.6077, 0.4757],
        [0.5874, 0.4363, 0.6339, 0.3208]])
tensor([[1.2528, 0.9407, 1.2153, 0.9515],
        [1.1747, 0.8727, 1.2679, 0.6415]])


In [14]:
a = torch.ones(4,3,2)
b = a * torch.rand(3,2)
print(b)

c = a * torch.rand(3,1)
print(c)

d = a * torch.rand(1,2)
print(d)

tensor([[[0.3132, 0.6331],
         [0.8222, 0.2652],
         [0.7328, 0.2126]],

        [[0.3132, 0.6331],
         [0.8222, 0.2652],
         [0.7328, 0.2126]],

        [[0.3132, 0.6331],
         [0.8222, 0.2652],
         [0.7328, 0.2126]],

        [[0.3132, 0.6331],
         [0.8222, 0.2652],
         [0.7328, 0.2126]]])
tensor([[[0.4408, 0.4408],
         [0.3877, 0.3877],
         [0.6078, 0.6078]],

        [[0.4408, 0.4408],
         [0.3877, 0.3877],
         [0.6078, 0.6078]],

        [[0.4408, 0.4408],
         [0.3877, 0.3877],
         [0.6078, 0.6078]],

        [[0.4408, 0.4408],
         [0.3877, 0.3877],
         [0.6078, 0.6078]]])
tensor([[[0.2345, 0.7117],
         [0.2345, 0.7117],
         [0.2345, 0.7117]],

        [[0.2345, 0.7117],
         [0.2345, 0.7117],
         [0.2345, 0.7117]],

        [[0.2345, 0.7117],
         [0.2345, 0.7117],
         [0.2345, 0.7117]],

        [[0.2345, 0.7117],
         [0.2345, 0.7117],
         [0.2345, 0.7117]]])


Look closely at the values of each tensor above:

- The multiplication operation that created b was broadcast over every “layer” of a.

- For c, the operation was broadcast over every layer and row of a - every 3-element column is identical.

- For d, we switched it around - now every row is identical, across layers and columns.



In [16]:
a = torch.ones(4,3,2)

b = a * torch.rand(4,3)     # dimensions must match last to first
c = a * torch.rand( 2,3)    # both 3rd and 2nd dims different
d = a * torch.rand((0,))    # can't broadcast with an empty tensor

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

## Altering Tensors in-place

There are times, though, that you may wish to alter a tensor in place - for example, if you’re doing an element-wise computation where you can discard intermediate values. For this, most of the math functions have a version with an appended underscore (_) that will alter a tensor in place.

In [18]:
a = torch.rand(2,6)
b = torch.rand(2,6)
print(a)
print(b)

a.add_(b)
print(a)

b.mul_(b)
print(b)

tensor([[0.0425, 0.0313, 0.5074, 0.7209, 0.6635, 0.1084],
        [0.1523, 0.8454, 0.1194, 0.7245, 0.6522, 0.1779]])
tensor([[0.7497, 0.9760, 0.5971, 0.3992, 0.9713, 0.3280],
        [0.5546, 0.6437, 0.6709, 0.2887, 0.3544, 0.3579]])
tensor([[0.7922, 1.0073, 1.1045, 1.1202, 1.6349, 0.4364],
        [0.7069, 1.4891, 0.7903, 1.0132, 1.0066, 0.5358]])
tensor([[0.5620, 0.9525, 0.3565, 0.1594, 0.9435, 0.1076],
        [0.3075, 0.4144, 0.4501, 0.0833, 0.1256, 0.1281]])


In [19]:
a = torch.rand(2,2)
b = torch.rand(2,2)
c = torch.zeros(2,2)

d = torch.matmul(a,b, out=c)
print(d, "\n", c)

tensor([[0.4170, 0.1459],
        [0.5558, 0.1531]]) 
 tensor([[0.4170, 0.1459],
        [0.5558, 0.1531]])


## Copying Tensors

As with any object in python, assigning a tensor to a variable makes the variable a label of the tensor, and does not copy it. BUt if you want a separate copy, `clone()` method is used.

In [20]:
a = torch.ones(2,2)
b = a

a[0][1] = 561
print(b)

tensor([[  1., 561.],
        [  1.,   1.]])


There is an important thing to be aware of when using ``clone()``. If your source tensor has autograd, enabled then so will the clone. Use `.detach()` to turn off the autograd for faster computations needed for forward pass. 

## Moving to accelerator

By default new tensors are created on the CPU, so we have to specify when we want to create our tensor on the accelerator with the optional `device` argument.

In [21]:
my_device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2,2, device=my_device)
print(x)

Device: mps
tensor([[0.2172, 0.3683],
        [0.0173, 0.0119]], device='mps:0')


It is important to know that in order to do computation involving two or more tensors, all of the tensors must be on the same device. 

## Manipulating Tensor shapes

In [22]:
a = torch.rand(3,226,226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


The unsqueeze() method adds a dimension of extent 1. unsqueeze(0) adds it as a new zeroth dimension - now you have a batch of one!

In [24]:
c = a.unsqueeze(1)
d = a.unsqueeze(2)
e = a.unsqueeze(3)
print(c.shape, "\n", d.shape, "\n", e.shape)

torch.Size([3, 1, 226, 226]) 
 torch.Size([3, 226, 1, 226]) 
 torch.Size([3, 226, 226, 1])


You may only squeeze() dimensions of extent 1. Calls to squeeze() and unsqueeze() can only act on dimensions of extent 1 because to do otherwise would change the number of elements in the tensor.

In [25]:
a = torch.rand(1,20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2,2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.9062, 0.2904, 0.2634, 0.6897, 0.3774, 0.0906, 0.3839, 0.4696, 0.2363,
         0.4035, 0.5047, 0.6997, 0.0530, 0.2326, 0.0159, 0.0429, 0.3702, 0.2488,
         0.9021, 0.2889]])
torch.Size([20])
tensor([0.9062, 0.2904, 0.2634, 0.6897, 0.3774, 0.0906, 0.3839, 0.4696, 0.2363,
        0.4035, 0.5047, 0.6997, 0.0530, 0.2326, 0.0159, 0.0429, 0.3702, 0.2488,
        0.9021, 0.2889])
torch.Size([2, 2])
torch.Size([2, 2])


The `squeeze()` and `unsqueeze()` methods also have in-place versions, `squeeze_()` and `unsqueeze_()`:

When it can, reshape() will return a view on the tensor to be changed - that is, a separate tensor object looking at the same underlying region of memory. This is important: That means any change made to the source tensor will be reflected in the view on that tensor, unless you clone() it.



In [26]:
output3d = torch.rand(6,20,20)
print(output3d.shape)

input1d = output3d.reshape(6*20*20)
print(input1d.shape)

# can also call it as a method on the torch module
print(torch.reshape(output3d, (6*20*20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])
